import { createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { and, eq, sql } from "drizzle-orm";
import { getDb } from "./db/client";
import { isMissingSchemaError } from "./db/pg-errors";
import { webhooks } from "./db/schema";
import { logServerError } from "./util/log";

// ============================================================
// Vouch — webhook notifications (2026-08-05 R&D, C-9).
//
// WHY. Vouch was a pull-only API: a customer who gated x402 settlement on a
// score had no way to learn that the world changed BETWEEN their lookups —
// an agent they had scored got blacklisted, or an outcome landed on a verdict
// they were issued. Polling every wallet they ever scored is exactly the
// N-requests-burning pattern the quota system exists to discourage. Webhooks
// turn the score API into a monitoring service, which is what "trust layer"
// has to mean in practice.
//
// EVENTS (deliberately few, all facts rather than scores):
//   list.changed      — the customer's own manual list changed (audit trail
//                       for team accounts; also fires on import).
//   outcome.recorded  — an outcome (auto-detected or partner-reported)
//                       landed on a verdict THIS customer requested.
// A score itself is never pushed: scores are computed on demand and pushing
// cached ones would invite treating a stale number as fresh.
//
// SECURITY POSTURE:
//   - Deliveries are signed (Stripe-style `t=<unix>,v1=<hmac>` over
//     `${t}.${body}`) so the receiver can authenticate us and reject replays.
//   - Webhook URLs are validated against SSRF at registration AND at delivery
//     time (a DNS record can change between the two).
//   - Delivery must never block or fail the request that triggered it:
//     fire-and-forget with a hard timeout, failures only counted.
//   - Consecutive failures auto-disable the endpoint (dead URLs stop costing
//     us egress and stop masking real delivery rates).
//   - The signing secret is generated by us (never chosen by the caller) and
//     shown once at registration, same contract as API keys.
// ============================================================

export const WEBHOOK_EVENTS = ["list.changed", "outcome.recorded", "watch.verdict_changed"] as const;
export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];

export const MAX_WEBHOOKS_PER_KEY = 5;
export const DISABLE_AFTER_FAILURES = 20;
const DELIVERY_TIMEOUT_MS = 5_000;

// ---- pure helpers (unit-tested without a database) -------------------------

export function isWebhookEvent(v: string): v is WebhookEvent {
  return (WEBHOOK_EVENTS as readonly string[]).includes(v);
}

/**
 * SSRF guard. Registration takes an arbitrary URL from an authenticated
 * customer and our server then POSTs to it — the classic pivot into
 * link-local metadata services and internal hosts. Allow only https to a
 * public-looking hostname. Hostname-literal IPs in private/reserved ranges
 * are rejected outright; names are re-checked at delivery time too.
 */
export function isSafeWebhookUrl(raw: string): boolean {
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false;
  }
  if (url.protocol !== "https:") return false;
  if (url.username || url.password) return false;
  const host = url.hostname.toLowerCase();
  if (host === "localhost" || host.endsWith(".localhost") || host.endsWith(".local")) return false;
  if (host.endsWith(".internal") || host === "metadata.google.internal") return false;
  // IPv6 literal
  if (host.startsWith("[") || host.includes(":")) return false;
  // IPv4 literal in private/reserved space
  const v4 = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(host);
  if (v4) {
    const [a, b] = [Number(v4[1]), Number(v4[2])];
    if (a === 0 || a === 10 || a === 127 || a >= 224) return false;
    if (a === 169 && b === 254) return false;
    if (a === 172 && b >= 16 && b <= 31) return false;
    if (a === 192 && b === 168) return false;
    if (a === 100 && b >= 64 && b <= 127) return false; // CGNAT
  }
  if (!host.includes(".") && !v4) return false; // bare single-label names are internal
  return true;
}

export function generateWebhookSecret(): string {
  return `whsec_${randomBytes(24).toString("base64url")}`;
}

/** `t=<unix seconds>,v1=<hex hmac of "<t>.<body>">` */
export function signWebhookPayload(secret: string, body: string, timestampSec: number): string {
  const v1 = createHmac("sha256", secret).update(`${timestampSec}.${body}`).digest("hex");
  return `t=${timestampSec},v1=${v1}`;
}

/** Receiver-side verification — exported so the docs can point at the exact
 *  algorithm and the SDK can ship it. Tolerance guards replays. */
export function verifyWebhookSignature(
  secret: string,
  body: string,
  header: string,
  nowSec: number,
  toleranceSec = 300,
): boolean {
  const parts = new Map(
    header.split(",").map((p) => {
      const i = p.indexOf("=");
      return [p.slice(0, i), p.slice(i + 1)] as const;
    }),
  );
  const t = Number(parts.get("t"));
  const v1 = parts.get("v1");
  if (!Number.isFinite(t) || !v1) return false;
  if (Math.abs(nowSec - t) > toleranceSec) return false;
  const expected = createHmac("sha256", secret).update(`${t}.${body}`).digest("hex");
  const a = Buffer.from(expected);
  const b = Buffer.from(v1);
  return a.length === b.length && timingSafeEqual(a, b);
}

// ---- persistence -----------------------------------------------------------

export interface WebhookRow {
  id: string;
  apiKeyId: string;
  url: string;
  secret: string;
  events: string[];
  active: boolean;
}

export async function listWebhooks(apiKeyId: string): Promise<Omit<WebhookRow, "secret">[]> {
  const db = getDb();
  if (!db) return [];
  try {
    const rows = await db
      .select({
        id: webhooks.id,
        apiKeyId: webhooks.apiKeyId,
        url: webhooks.url,
        events: webhooks.events,
        active: webhooks.active,
      })
      .from(webhooks)
      .where(eq(webhooks.apiKeyId, apiKeyId));
    return rows.map((r) => ({ ...r, events: (r.events as string[]) ?? [] }));
  } catch (error) {
    if (isMissingSchemaError(error)) return [];
    throw error;
  }
}

export async function createWebhook(params: {
  apiKeyId: string;
  url: string;
  events: WebhookEvent[];
}): Promise<{ id: string; secret: string } | { error: "limit_reached" | "store_unavailable" }> {
  const db = getDb();
  if (!db) return { error: "store_unavailable" };
  try {
    const existing = await db
      .select({ n: sql<number>`count(*)` })
      .from(webhooks)
      .where(eq(webhooks.apiKeyId, params.apiKeyId));
    if (Number(existing[0]?.n ?? 0) >= MAX_WEBHOOKS_PER_KEY) {
      return { error: "limit_reached" };
    }
    const secret = generateWebhookSecret();
    const inserted = await db
      .insert(webhooks)
      .values({
        apiKeyId: params.apiKeyId,
        url: params.url,
        secret,
        events: params.events,
        active: true,
      })
      .returning();
    return { id: inserted[0]!.id, secret };
  } catch (error) {
    if (isMissingSchemaError(error)) return { error: "store_unavailable" };
    throw error;
  }
}

export async function deleteWebhook(apiKeyId: string, id: string): Promise<boolean> {
  const db = getDb();
  if (!db) return false;
  try {
    const deleted = await db
      .delete(webhooks)
      .where(and(eq(webhooks.id, id), eq(webhooks.apiKeyId, apiKeyId)))
      .returning();
    return deleted.length > 0;
  } catch (error) {
    if (isMissingSchemaError(error)) return false;
    throw error;
  }
}

// ---- delivery --------------------------------------------------------------

async function deliverOne(row: WebhookRow, eventType: WebhookEvent, payload: unknown): Promise<void> {
  const db = getDb();
  // Re-validate at delivery time: the URL was checked at registration, but
  // this is the moment we actually egress.
  if (!isSafeWebhookUrl(row.url)) {
    return;
  }
  const body = JSON.stringify({
    id: `evt_${randomBytes(12).toString("base64url")}`,
    type: eventType,
    createdAt: new Date().toISOString(),
    data: payload,
  });
  const signature = signWebhookPayload(row.secret, body, Math.floor(Date.now() / 1000));

  let ok = false;
  try {
    const res = await fetch(row.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Vouch-Signature": signature,
        "User-Agent": "vouch-webhooks/1",
      },
      body,
      redirect: "error", // a redirect at delivery time is an SSRF vector, not a feature
      signal: AbortSignal.timeout(DELIVERY_TIMEOUT_MS),
    });
    ok = res.ok;
  } catch {
    ok = false;
  }

  if (!db) return;
  try {
    if (ok) {
      await db
        .update(webhooks)
        .set({ failureCount: 0, lastDeliveredAt: new Date() })
        .where(eq(webhooks.id, row.id));
    } else {
      await db
        .update(webhooks)
        .set({
          failureCount: sql`${webhooks.failureCount} + 1`,
          active: sql`CASE WHEN ${webhooks.failureCount} + 1 >= ${DISABLE_AFTER_FAILURES} THEN false ELSE ${webhooks.active} END`,
        })
        .where(eq(webhooks.id, row.id));
    }
  } catch (error) {
    if (!isMissingSchemaError(error)) logServerError("webhook_bookkeeping", error);
  }
}

/**
 * Fire an event at every active endpoint the api key has subscribed to it.
 * Fire-and-forget by contract: callers `void` this — a webhook must never
 * slow down or fail the request that triggered it.
 */
export async function dispatchWebhookEvent(
  apiKeyId: string | null,
  eventType: WebhookEvent,
  payload: unknown,
): Promise<void> {
  if (!apiKeyId) return;
  const db = getDb();
  if (!db) return;
  let rows: WebhookRow[];
  try {
    const found = await db
      .select()
      .from(webhooks)
      .where(and(eq(webhooks.apiKeyId, apiKeyId), eq(webhooks.active, true)));
    rows = found.map((r) => ({
      id: r.id,
      apiKeyId: r.apiKeyId,
      url: r.url,
      secret: r.secret,
      events: (r.events as string[]) ?? [],
      active: r.active,
    }));
  } catch (error) {
    if (!isMissingSchemaError(error)) logServerError("webhook_lookup", error);
    return;
  }

  await Promise.all(
    rows
      .filter((r) => r.events.includes(eventType))
      .map((r) =>
        deliverOne(r, eventType, payload).catch((error) => logServerError("webhook_delivery", error)),
      ),
  );
}
